package com.kevin.astra.domain.vision

internal object ImagenetLabels {
    val LABELS = listOf(
        "background","tench","goldfish","great white shark","tiger shark","hammerhead",
        "electric ray","stingray","cock","hen","ostrich","brambling","goldfinch",
        "house finch","junco","indigo bunting","robin","bulbul","jay","magpie",
        "chickadee","water ouzel","kite","bald eagle","vulture","great grey owl",
        "fire salamander","smooth newt","eft","spotted salamander","axolotl",
        "bullfrog","tree frog","tailed frog","loggerhead","leatherback turtle",
        "mud turtle","terrapin","box turtle","banded gecko","common iguana",
        "American chameleon","whiptail lizard","agama","frilled lizard",
        "alligator lizard","Gila monster","green lizard","African chameleon",
        "Komodo dragon","African crocodile","American alligator","triceratops",
        "thunder snake","ringneck snake","hognose snake","green snake","king snake",
        "garter snake","water snake","vine snake","night snake","boa constrictor",
        "rock python","Indian cobra","green mamba","sea snake","horned viper",
        "diamondback rattlesnake","sidewinder","trilobite","harvestman","scorpion",
        "black widow","tarantula","wolf spider","tick","centipede","grouse",
        "ptarmigan","ruffed grouse","prairie chicken","peacock","quail","partridge",
        "African grey parrot","macaw","cockatoo","lorikeet","coucal","bee eater",
        "hornbill","hummingbird","jacamar","toucan","drake","red-breasted merganser",
        "goose","black swan","tusker","echidna","platypus","wallaby","koala",
        "wombat","jellyfish","sea anemone","brain coral","flatworm","nematode",
        "conch","snail","slug","sea slug","chiton","sea urchin","sea cucumber",
        "card","cup","laptop","keyboard","mouse","monitor","desk","chair","book",
        "pen","pencil","notebook","phone","smartphone","camera","bicycle","car",
        "bus","truck","airplane","boat","traffic light","fire hydrant","stop sign",
        "parking meter","bench","bird","cat","dog","horse","sheep","cow","elephant",
        "bear","zebra","giraffe","backpack","umbrella","handbag","tie","suitcase",
        "frisbee","skis","snowboard","sports ball","kite","baseball bat",
        "baseball glove","skateboard","surfboard","tennis racket","bottle",
        "wine glass","cup","fork","knife","spoon","bowl","banana","apple",
        "sandwich","orange","broccoli","carrot","hot dog","pizza","donut","cake",
        "couch","potted plant","bed","dining table","toilet","tv","laptop",
        "mouse","remote","keyboard","cell phone","microwave","oven","toaster",
        "sink","refrigerator","book","clock","vase","scissors","teddy bear",
        "hair drier","toothbrush","coffee mug","water bottle","backpack","hat",
        "sunglasses","watch","necklace","tree","flower","grass","mountain","sky",
        "ocean","river","road","building","house","bridge","fence","sign",
        "street light","fire","smoke","rain","snow","cloud","sun","moon",
        "person","face","hand","arm","leg","foot","hair","eye","ear","nose","mouth"
    )
}
