package com.kevin.astra.core.ai

import kotlinx.coroutines.runBlocking
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

class LiteRtLmInferenceEngineTest {
    @Test
    fun reportsModelMissingAndFallsBackSafely() = runBlocking {
        val engine = LiteRtLmInferenceEngine(
            modelLoader = object : LiteRtLmModelLoader {
                override suspend fun loadModel(request: PromptRequest): LiteRtLmModelLoadResult =
                    LiteRtLmModelLoadResult.Missing("bundle missing")
            },
            fallbackEngine = MockInferenceEngine(timestampProvider = { "timestamp" }),
        )

        val result = engine.generate(testRequest())

        assertEquals(InferenceBackend.Mock, result.backend)
        assertEquals(RuntimeMode.ModelMissing, result.runtimeInfo.mode)
        assertEquals("bundle missing", result.runtimeInfo.fallbackReason)
        assertTrue(result.text.contains("LiteRT-LM generative runtime not active"))
    }

    @Test
    fun reportsUnsupportedPlatformAndFallsBackSafely() = runBlocking {
        val engine = LiteRtLmInferenceEngine(
            modelLoader = UnsupportedLiteRtLmModelLoader("unsupported platform"),
            fallbackEngine = MockInferenceEngine(timestampProvider = { "timestamp" }),
        )

        val result = engine.generate(testRequest())

        assertEquals(InferenceBackend.Mock, result.backend)
        assertEquals(RuntimeMode.UnsupportedPlatform, result.runtimeInfo.mode)
        assertEquals("unsupported platform", result.runtimeInfo.fallbackReason)
    }

    @Test
    fun reportsGenerativeRuntimeSkeletonWhenBundleExists() = runBlocking {
        val engine = LiteRtLmInferenceEngine(
            modelLoader = object : LiteRtLmModelLoader {
                override suspend fun loadModel(request: PromptRequest): LiteRtLmModelLoadResult =
                    LiteRtLmModelLoadResult.Loaded(
                        LiteRtLmModelBundle(
                            id = "gemma",
                            displayName = "Gemma",
                            rootPath = "models/litert-lm",
                            modelPath = "/cache/gemma.task",
                            sourceModelPath = "models/litert-lm/gemma.task",
                            sizeBytes = 1024,
                        ),
                    )
            },
            runtimeSession = object : LiteRtLmRuntimeSession {
                override suspend fun generate(
                    request: PromptRequest,
                    bundle: LiteRtLmModelBundle,
                ): GenerationResult =
                    GenerationResult(
                        text = "Generated by Gemma LiteRT-LM.",
                        metrics = GenerationMetrics(
                            latencyMillis = 42,
                            timeToFirstTokenMillis = 42,
                            tokensGenerated = 6,
                            tokensPerSecond = 142,
                            memoryUsageMb = 1,
                        ),
                        model = request.model,
                        backend = InferenceBackend.LiteRtLm,
                        generatedAt = "timestamp",
                        runtimeInfo = GenerationRuntimeInfo(
                            mode = RuntimeMode.LiteRtLmGenerative,
                            modelLoadTimeMillis = 7,
                            inferenceLatencyMillis = 42,
                            totalExecutionTimeMillis = 49,
                        ),
                    )

                override fun close() = Unit
            },
            fallbackEngine = MockInferenceEngine(timestampProvider = { "timestamp" }),
        )

        val result = engine.generate(testRequest())

        assertEquals(InferenceBackend.LiteRtLm, result.backend)
        assertEquals(RuntimeMode.LiteRtLmGenerative, result.runtimeInfo.mode)
        assertEquals("Generated by Gemma LiteRT-LM.", result.text)
        assertNull(result.runtimeInfo.fallbackReason)
    }

    @Test
    fun fallsBackWhenRealGenerativeSessionFails() = runBlocking {
        val engine = LiteRtLmInferenceEngine(
            modelLoader = object : LiteRtLmModelLoader {
                override suspend fun loadModel(request: PromptRequest): LiteRtLmModelLoadResult =
                    LiteRtLmModelLoadResult.Loaded(
                        LiteRtLmModelBundle(
                            id = "gemma",
                            displayName = "Gemma",
                            rootPath = "models/litert-lm",
                            modelPath = "/cache/gemma.task",
                            sourceModelPath = "models/litert-lm/gemma.task",
                        ),
                    )
            },
            runtimeSession = UnavailableLiteRtLmRuntimeSession("runtime failed"),
            fallbackEngine = MockInferenceEngine(timestampProvider = { "timestamp" }),
        )

        val result = engine.generate(testRequest())

        assertEquals(InferenceBackend.Mock, result.backend)
        assertEquals(RuntimeMode.Fallback, result.runtimeInfo.mode)
        assertEquals("runtime failed", result.runtimeInfo.fallbackReason)
    }

    private fun testRequest(): PromptRequest =
        PromptRequest(
            prompt = "Diagnose a pump issue.",
            industry = PromptIndustry.IndustrialMaintenance,
            model = AiModel.Gemma,
            backend = InferenceBackend.LiteRtLm,
            maxTokens = 128,
            temperature = 0.2,
        )
}
